# Generated by Django 6.1 on 2026-09-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_product_image_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ডকুমেন্টের নাম (যেমন: ট্রেড লাইসেন্স / ভোটার আইডি)')),
                ('image', models.ImageField(upload_to='legal_docs/', verbose_name='ডকুমেন্টের ছবি')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Legal Document',
                'verbose_name_plural': 'Legal Documents',
            },
        ),
    ]
